import { sql } from 'drizzle-orm';
import {
  bigint,
  check,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

export const fileStatus = pgEnum('file_status', [
  'pending',
  'uploading',
  'scanning',
  'ready',
  'blocked',
  'expired',
  'deleted',
  'failed',
]);

export const uploadSessionStatus = pgEnum('upload_session_status', [
  'pending',
  'completed',
  'aborted',
  'expired',
]);

export const jobStatus = pgEnum('job_status', ['queued', 'running', 'succeeded', 'failed', 'dead']);

/**
 * Accounts are not used by the anonymous MVP flow, but the table and the
 * nullable `files.owner_id` exist so that adding sign-in later is a feature,
 * not a migration of every existing row.
 */
export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: text('email').notNull(),
    passwordHash: text('password_hash').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('users_email_lower_unique').on(sql`lower(${table.email})`),
    check('users_email_not_blank', sql`length(btrim(${table.email})) > 0`),
  ],
);

export const files = pgTable(
  'files',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    ownerId: uuid('owner_id').references(() => users.id, { onDelete: 'set null' }),
    /** Random key generated by Toran. Never derived from user input. */
    storageKey: text('storage_key').notNull(),
    originalFilename: text('original_filename').notNull(),
    normalizedFilename: text('normalized_filename').notNull(),
    contentType: text('content_type').notNull(),
    declaredSize: bigint('declared_size', { mode: 'number' }).notNull(),
    /** Set from a storage HEAD after the browser reports completion. */
    actualSize: bigint('actual_size', { mode: 'number' }),
    checksum: text('checksum'),
    status: fileStatus('status').notNull().default('pending'),
    /** Rotating HMAC of the uploader's address. Never a raw IP. */
    anonIdentifier: text('anon_identifier'),
    /** Safe, operator-facing scan outcome, e.g. a ClamAV signature name. */
    scanResult: text('scan_result'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'date' }),
  },
  (table) => [
    uniqueIndex('files_storage_key_unique').on(table.storageKey),
    index('files_status_idx').on(table.status),
    // Drives the expiry sweep: only rows that can still expire are indexed.
    index('files_expires_at_idx')
      .on(table.expiresAt)
      .where(sql`${table.deletedAt} is null and ${table.expiresAt} is not null`),
    index('files_anon_identifier_idx')
      .on(table.anonIdentifier)
      .where(sql`${table.deletedAt} is null`),
    index('files_owner_idx').on(table.ownerId),
    index('files_created_at_idx').on(table.createdAt),
    check('files_declared_size_non_negative', sql`${table.declaredSize} >= 0`),
    check(
      'files_actual_size_non_negative',
      sql`${table.actualSize} is null or ${table.actualSize} >= 0`,
    ),
    check(
      'files_deleted_status_consistent',
      sql`(${table.deletedAt} is null) or (${table.status} in ('deleted', 'blocked'))`,
    ),
  ],
);

export const uploadSessions = pgTable(
  'upload_sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    fileId: uuid('file_id')
      .notNull()
      .references(() => files.id, { onDelete: 'cascade' }),
    status: uploadSessionStatus('status').notNull().default('pending'),
    /**
     * Vestigial. These held the link configuration requested when an upload
     * began, back when completing that upload also minted the link. A link may
     * now serve several files, so it cannot exist until all of them are stored:
     * `POST /api/shares` takes these settings instead, and the upload path
     * writes NULL here.
     *
     * Kept because migrations are additive and forward-only; dropping a column
     * is a deliberate, separately announced change. Nothing in the application
     * reads them.
     */
    sharePasswordHash: text('share_password_hash'),
    shareMaxDownloads: integer('share_max_downloads'),
    shareExpiresAt: timestamp('share_expires_at', { withTimezone: true, mode: 'date' }),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
    completedAt: timestamp('completed_at', { withTimezone: true, mode: 'date' }),
  },
  (table) => [
    // One session per file: makes duplicate completion requests collapse onto
    // a single row instead of racing to create a second.
    uniqueIndex('upload_sessions_file_id_unique').on(table.fileId),
    index('upload_sessions_expiry_idx')
      .on(table.expiresAt)
      .where(sql`${table.status} = 'pending'`),
    check(
      'upload_sessions_completed_consistent',
      sql`(${table.completedAt} is null) = (${table.status} <> 'completed')`,
    ),
    check(
      'upload_sessions_share_max_downloads_positive',
      sql`${table.shareMaxDownloads} is null or ${table.shareMaxDownloads} > 0`,
    ),
  ],
);

/**
 * A link. The files it serves live in `share_link_files`.
 *
 * `max_downloads` is a budget *per file*, not for the link as a whole: a
 * recipient exhausting one file must not make the others unreachable.
 */
export const shareLinks = pgTable(
  'share_links',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** SHA-256 of the raw token. The raw token is never stored. */
    tokenHash: text('token_hash').notNull(),
    passwordHash: text('password_hash'),
    expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }),
    maxDownloads: integer('max_downloads'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    revokedAt: timestamp('revoked_at', { withTimezone: true, mode: 'date' }),
  },
  (table) => [
    uniqueIndex('share_links_token_hash_unique').on(table.tokenHash),
    index('share_links_expires_at_idx')
      .on(table.expiresAt)
      .where(sql`${table.revokedAt} is null and ${table.expiresAt} is not null`),
    check(
      'share_links_max_downloads_positive',
      sql`${table.maxDownloads} is null or ${table.maxDownloads} > 0`,
    ),
  ],
);

/**
 * The files a link serves, one row each, each with its own download budget.
 *
 * `max_downloads` is copied from the link rather than joined to. A CHECK may
 * only reference its own row, and keeping the limit enforceable *by the
 * database* - not merely by the UPDATE in `reserveDownload` - is the point of
 * the constraint below. Both columns are written once when the link is created
 * and never updated, so the copy cannot drift.
 */
export const shareLinkFiles = pgTable(
  'share_link_files',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    shareLinkId: uuid('share_link_id')
      .notNull()
      .references(() => shareLinks.id, { onDelete: 'cascade' }),
    fileId: uuid('file_id')
      .notNull()
      .references(() => files.id, { onDelete: 'cascade' }),
    /** Order the uploader chose, so the download page is not arbitrary. */
    position: integer('position').notNull().default(0),
    maxDownloads: integer('max_downloads'),
    downloadCount: integer('download_count').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  },
  (table) => [
    // One row per file per link: a duplicated file cannot get two budgets.
    uniqueIndex('share_link_files_link_file_unique').on(table.shareLinkId, table.fileId),
    index('share_link_files_link_idx').on(table.shareLinkId),
    index('share_link_files_file_idx').on(table.fileId),
    check('share_link_files_download_count_non_negative', sql`${table.downloadCount} >= 0`),
    check(
      'share_link_files_max_downloads_positive',
      sql`${table.maxDownloads} is null or ${table.maxDownloads} > 0`,
    ),
    // Database-level backstop for the atomic reservation in `reserveDownload`.
    // Even a buggy or malicious writer cannot push a counter past its limit.
    check(
      'share_link_files_within_download_limit',
      sql`${table.maxDownloads} is null or ${table.downloadCount} <= ${table.maxDownloads}`,
    ),
  ],
);

export const downloadEvents = pgTable(
  'download_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    shareLinkId: uuid('share_link_id')
      .notNull()
      .references(() => shareLinks.id, { onDelete: 'cascade' }),
    /** Rotating HMAC. Never a raw IP address. */
    ipIdentifier: text('ip_identifier').notNull(),
    userAgent: text('user_agent').notNull().default(''),
    downloadedAt: timestamp('downloaded_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index('download_events_share_link_idx').on(table.shareLinkId),
    index('download_events_downloaded_at_idx').on(table.downloadedAt),
  ],
);

export const jobs = pgTable(
  'jobs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    type: text('type').notNull(),
    payload: jsonb('payload').notNull().default({}),
    status: jobStatus('status').notNull().default('queued'),
    attempts: integer('attempts').notNull().default(0),
    maxAttempts: integer('max_attempts').notNull().default(5),
    availableAt: timestamp('available_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    lockedAt: timestamp('locked_at', { withTimezone: true, mode: 'date' }),
    lockedBy: text('locked_by'),
    lastError: text('last_error'),
    /**
     * Optional idempotency key. Only one non-finished job may hold a given
     * value, so retried API calls and duplicate schedulers cannot enqueue the
     * same work twice.
     */
    dedupeKey: text('dedupe_key'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  },
  (table) => [
    // Claim query index: queued rows ordered by availability.
    index('jobs_claim_idx')
      .on(table.availableAt)
      .where(sql`${table.status} = 'queued'`),
    index('jobs_status_idx').on(table.status),
    index('jobs_type_idx').on(table.type),
    // Reclaim index for jobs whose worker died holding the lock.
    index('jobs_locked_at_idx')
      .on(table.lockedAt)
      .where(sql`${table.status} = 'running'`),
    uniqueIndex('jobs_dedupe_key_unique')
      .on(table.dedupeKey)
      .where(sql`${table.dedupeKey} is not null and ${table.status} in ('queued', 'running')`),
    check('jobs_attempts_non_negative', sql`${table.attempts} >= 0`),
    check('jobs_max_attempts_positive', sql`${table.maxAttempts} >= 1`),
  ],
);

/**
 * Fixed-window counters for the PostgreSQL rate limiter. Rows are disposable;
 * the cleanup job prunes windows that can no longer be current.
 */
export const rateLimits = pgTable(
  'rate_limits',
  {
    key: text('key').notNull(),
    windowStart: timestamp('window_start', { withTimezone: true, mode: 'date' }).notNull(),
    count: integer('count').notNull().default(0),
    expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
  },
  (table) => [
    uniqueIndex('rate_limits_key_window_unique').on(table.key, table.windowStart),
    index('rate_limits_expires_at_idx').on(table.expiresAt),
    check('rate_limits_count_non_negative', sql`${table.count} >= 0`),
  ],
);

export type UserRow = typeof users.$inferSelect;
export type FileRow = typeof files.$inferSelect;
export type NewFileRow = typeof files.$inferInsert;
export type UploadSessionRow = typeof uploadSessions.$inferSelect;
export type ShareLinkRow = typeof shareLinks.$inferSelect;
export type ShareLinkFileRow = typeof shareLinkFiles.$inferSelect;
export type DownloadEventRow = typeof downloadEvents.$inferSelect;
export type JobRow = typeof jobs.$inferSelect;
